name: hd-vis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - jupyterlab
  - zarr
  - snakemake
  - requests
  - psycopg2
  - pip
  - pip:
    - peewee