name: hd-vis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - jupyterlab
  - zarr
  - snakemake
  - requests
  - psycopg2
  - altair==4.2.2
  - altair_saver==0.5.0
  - selenium==4.2.0
  - mpltern==1.0.2
  - seaborn==0.13.0
  - pip
  - pip:
    - peewee
